version: '3'

services:
  app:
    build: .
    container_name: ums_backend
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=${PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - '8800:8800'
    depends_on:
      - redis
    command: node index.js

  worker:
    build: .
    container_name: ums_worker
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - redis
    command: node workers/notification.worker.js

  redis:
    image: redis:alpine
    container_name: ums_redis
    ports:
      - '6379:6379'
